version: "3.7"
services:
  app:
    build:
      args:
        user: frane
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: lara-graphql
    container_name: laragraphl-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laraapp

  db:
    image: mysql:5.7
    container_name: laraapp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laraapp
    volumes:
      - /opt/mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: laraapp-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - laraapp

networks:
  laraapp:
    driver: bridge
